
  data:
    rest:
      base-path: /api
      default-page-size: 10
      max-page-size: 10

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
