server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/meeting?serverTimezone=Asia/Seoul
    username: root
    password: min753951
    driver-class-name: com.mysql.jdbc.Driver
  data:
    rest:
      base-path: /api
      default-page-size: 10
      max-page-size: 10

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
